name: LaTeX Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra latexmk

      - name: Compile LaTeX documents
        run: |
          find . -name "*.tex" -type f -exec sh -c '
            for texfile do
              filename=$(basename "$texfile" .tex)
              directory=$(dirname "$texfile")
              echo "Compiling $texfile..."
              cd "$directory"
              latexmk -pdf \
                -interaction=nonstopmode \
                -file-line-error \
                -synctex=1 \
                -pdflatex="pdflatex -shell-escape -interaction=nonstopmode -file-line-error %O %S" \
                "$filename.tex"
              cd - > /dev/null
            done
          ' sh {} +

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: user-guide
          path: |
            **/*.pdf